// Adapter central de ícones — trocar a biblioteca inteira = mexer SÓ neste arquivo.
// Hoje aponta para o Phosphor (o peso "duotone" é definido via IconContext em main.jsx),
// que dá uma cara mais personalizada que o @tabler. Os nomes seguem o padrão "IconX" que o
// app já usava (IconHome, IconBulb…), então cada componente mudou apenas o caminho do import.
export {
  House as IconHome,
  Kanban as IconLayoutKanban,
  Lightbulb as IconBulb,
  CalendarBlank as IconCalendar,
  ListChecks as IconListCheck,
  UsersThree as IconUsers,
  SignOut as IconLogout,
  Target as IconTarget,
  UserGear as IconUserCog,
  X as IconX,
  Camera as IconCamera,
  CurrencyDollar as IconCurrencyDollar,
  Trophy as IconTrophy,
  Megaphone as IconSpeakerphone,
  Clock as IconClock,
  CaretRight as IconChevronRight,
  Desktop as IconDeviceDesktop,
  DeviceMobile as IconDeviceMobile,
  Moon as IconMoon,
  Sun as IconSun,
  Check as IconCheck,
  ArrowLeft as IconArrowLeft,
  Copy as IconCopy,
  MagicWand as IconWand,
  Eye as IconEye,
  DownloadSimple as IconDownload,
  MagnifyingGlass as IconSearch,
  TrendUp as IconTrendingUp,
  TrendDown as IconTrendingDown,
  Play as IconPlayerPlay,
  Image as IconPhoto,
  ChatText as IconMessage,
  LinkSimple as IconLink,
  PencilSimple as IconPencil,
  Pulse as IconActivity,
  CreditCard as IconCreditCard,
  ChartBar as IconChartBar,
  PlugsConnected as IconPlugConnected,
  CheckCircle as IconCircleCheck,
  ArrowSquareOut as IconExternalLink,
  ArrowsClockwise as IconRefresh,
  Globe as IconWorld,
  Plus as IconPlus,
  Trash as IconTrash,
  Rocket as IconRocket,
} from "@phosphor-icons/react";
